### ISSUE TITLE
Solver's Status

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/Solve4x#8]
I've been working on the solver lately. It should be done in a couple of days (depending on how things go). After that I intend to write a wiki article explaining how to define a solving strategy. We'll need lots of those in order to power the solver.
More updates to come.

**Comment by Nateowami** [comment]
4<sup>th</sup> and inches. I'm _so_ close to having combining terms done. Unfortunately, `-2+6` is parsed as the expression being negative as a whole, i.e., `-(2+6)` which is `-8` instead of `4`. Similar to the issue with exponents, but this time it only applies to expressions, nothing else. Probably needs to be a hard-coded exception in `AlgebraicParticle`.
> `AlgebraicParticle throws new HardCodedException();`

**Comment by Nateowami** [comment]
Yay! It can now solve `4x+5x-8x=2(1)/(3)+6(1)/(3)-4`. Here's the output:

```
Solution for 4x+5x-8x=2(1)/(3)+6(1)/(3)-4

Step 1: 
Here's the original equation.
	4x+5x-8x=2(1)/(3)+6(1)/(3)-4
Step 2: 
We need to combine like terms here, in the expression 4x+5x-8x.
Combine 4x, 5x, and -8x to get x.

	x=2(1)/(3)+6(1)/(3)-4
Step 3: 
We need to combine like terms here, in the expression 2(1)/(3)+6(1)/(3)-4.
Combine 2(1)/(3) and 6(1)/(3) to get 8(2)/(3).
Combine -4 to get -4.

	x=8(2)/(3)-4
Step 4: 
We need to combine like terms here, in the expression 8(2)/(3)-4.
Combine 8(2)/(3) and -4 to get 4(2)/(3).

	x=4(2)/(3)
```

**Comment by Tribex** [comment]
Excellent! Looking great!

**Comment by Nateowami** [comment]
Closing now as this has turned more into a blog and the solver isn't changing as much these days. Issues will make more sense once the main feature set is in place.
